// L2 cpp-catch2 TEMPLATE test harness. Do NOT hand this file's authorship to students —
// it ships in the Starter unchanged ("Do NOT edit this file!").
//
// Four tag groups: [T1] [T2] [T3] [T4], 20 points each; classroom.yml runs one grader per tag.
// Per assignment: replace every placeholder with real SECTIONs/TEST_CASEs.
//
// RULES (see git-asmt-repo/languages/cpp-catch2.md and L1 §3/§5):
//  - REQUIRE the function's RETURN value (or the state it filled), never scraped stdout.
//  - Cover the edges the spec implies: empty, single, negatives, duplicates, boundary, largest-N.
//  - A group is NOT one test: add as many items per group as the problem needs, so every
//    case the spec implies is exercised. But only test edges the INSTRUCTION states —
//    an unstated case (e.g. negatives when the spec never allows them) is a trap; fix the
//    instruction first, then test it (L1 §3).
//  - The placeholders below FAIL on purpose. A placeholder that passes is a silent hole (L1 GATE A).
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("T1 placeholder — replace with real cases", "[T1]")
{
    FAIL("TODO: replace with real T1 cases for this assignment");
}

TEST_CASE("T2 placeholder — replace with real cases", "[T2]")
{
    FAIL("TODO: replace with real T2 cases for this assignment");
}

TEST_CASE("T3 placeholder — replace with real cases", "[T3]")
{
    FAIL("TODO: replace with real T3 cases for this assignment");
}

TEST_CASE("T4 placeholder — replace with real cases", "[T4]")
{
    FAIL("TODO: replace with real T4 cases for this assignment");
}
